[build]
  publish = "public"
  functions = "netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
